# see https://symfony.com/doc/current/reference/configuration/framework.html


    # Note that the session will be started ONLY if you read or write from it.
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection:
        enabled: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true


when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
